/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "contactformpwa",
            "endpoint": "https://6srbe7uzgd.execute-api.us-east-1.amazonaws.com/production",
            "region": "us-east-1"
        },
        {
            "name": "webauthn",
            "endpoint": "https://qls9aymov0.execute-api.us-east-1.amazonaws.com/production",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "whatpwacandotoday-20191219194136-hostingbucket-production",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d5rbblcrnyxpk.cloudfront.net"
};


export default awsmobile;
